#!/usr/bin/env python3
"""
Phase 2.2 — Vision re-verification of Photos Library labels.

The Photos Library labels in ~/.gst-ingest-state.json were generated by
Sonnet vision before the decal-evidence guard was added. ~10-15% are wrong
at brand level (e.g., "Tadano AC 500-2" — AC 500-2 is Demag, not Tadano).

This script re-asks Sonnet 4.6 Vision for each Photos Library row, with a
hardened prompt that requires decal evidence for the brand claim. Vision's
new answer overrides the noisy ingest label.

Manifest rows are NOT re-verified — those are human-tagged at the source.

Cost budget: $40 hard cap. Estimated $25-30 for 8,065 photos at batch=3,
max 768px.

Output:
  outputs/cleaned_labels.csv  — verified Photos Library labels
  state/vision_progress.json  — resumable state
  outputs/needs_review.csv    — rows where Vision was uncertain (<0.7 conf)
"""

import base64
import csv
import io
import json
import os
import sys
import time
from pathlib import Path

from PIL import Image
import anthropic

ROOT = Path(__file__).parent.parent
RAW_LABELS = ROOT / "outputs/raw_labels.csv"
CLEAN_OUT = ROOT / "outputs/cleaned_labels.csv"
REVIEW_OUT = ROOT / "outputs/needs_review.csv"
STATE_FILE = ROOT / "state/vision_progress.json"
STATE_FILE.parent.mkdir(parents=True, exist_ok=True)

MODEL = "claude-sonnet-4-6"
BATCH = 3
MAX_DIM = 768
COST_CAP_USD = 40.0  # Hard stop. PLAN.md estimated ~$30; this is safety net.

# Sonnet 4.6 pricing per 1M tokens (input/output)
PRICE_IN = 3.0 / 1_000_000
PRICE_OUT = 15.0 / 1_000_000

PROMPT = """You are looking at {n} photographs of mobile/all-terrain cranes. \
For EACH image, your ONLY job is to transcribe text visible on the crane body — \
brand badges, model decals, chassis nameplates, painted text. Do NOT interpret, \
classify, or guess from chassis shape. If you can't read text, return empty string.

For each image, return:
- visible_text: exact text transcription, all readable brand/model markings concatenated \
with " | " separators (e.g., "LIEBHERR | LTM 1500-8.1" or "TADANO FAUN" or "")
- text_confidence: 0.0-1.0 — how clearly the text is legible

Return STRICT JSON, exactly {n} entries in order:
{{"results": [{{"visible_text": "...", "text_confidence": 0.8}}, ...]}}"""

# Keyword → brand mapping. Captures lineage (Faun→Tadano, Demag→Terex-Demag)
BRAND_KEYWORDS = {
    "Liebherr": ["LIEBHERR", "LTM ", "LTM-", "LR ", "LR-", "LG ", "LG-", "LTC ", "LTF ", "LTR "],
    "Tadano": ["TADANO", "FAUN", "ATF ", "ATF-", " GR ", " GR-", " AR-"],
    "Grove": ["GROVE", "GMK", " RT "],
    "Terex-Demag": ["DEMAG", "TEREX", "AC ", "AC-", "CC ", "CC-", "TC ", "TC-", " HC "],
}


def detect_brand_from_text(text: str) -> str | None:
    """Return brand if any keyword matches, else None."""
    if not text:
        return None
    t = " " + text.upper() + " "
    matches = []
    for brand, keywords in BRAND_KEYWORDS.items():
        for kw in keywords:
            if kw in t:
                matches.append(brand)
                break
    # If multiple brand matches (e.g., the photo has multiple cranes), reject as ambiguous
    return matches[0] if len(set(matches)) == 1 else None


import re
def detect_model_from_text(text: str, brand: str | None) -> str | None:
    """Extract model digits if visible. e.g., 'LIEBHERR LTM 1500-8.1' → 'LTM 1500-8.1'."""
    if not text or not brand:
        return None
    T = text.upper()
    patterns = {
        "Liebherr": [r"LTM[- ]?\d{4}[- ]?\d?\.?\d?", r"LR[- ]?\d{3,5}(/\d)?", r"LG[- ]?\d{4}",
                     r"LTC[- ]?\d{4}[- ]?\d?\.?\d?", r"LTF[- ]?\d{4}[- ]?\d?\.?\d?"],
        "Tadano": [r"ATF[- ]?\d{2,3}G?[- ]?\d?", r"AC[- ]?\d{2,3}[- ]?\d?", r"GR[- ]?\d{2,4}"],
        "Grove": [r"GMK[ -]?\d{4}[A-Z]?[- ]?\d?", r"RT[- ]?\d{3,4}"],
        "Terex-Demag": [r"AC[- ]?\d{2,4}[- ]?\d?", r"CC[- ]?\d{3,5}[- ]?\d?",
                         r"TC[- ]?\d{2,4}", r"HC[- ]?\d{2,4}"],
    }
    for pat in patterns.get(brand, []):
        m = re.search(pat, T)
        if m:
            return m.group(0).strip()
    return None


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"done": {}, "spent_usd": 0.0}


def save_state(s):
    STATE_FILE.write_text(json.dumps(s))


def downscale_to_b64(path: Path, max_dim: int) -> tuple[str, str] | None:
    try:
        img = Image.open(path)
    except Exception as e:
        print(f"[!] open failed {path}: {e}", file=sys.stderr)
        return None
    img = img.convert("RGB")
    # Scale longest side to max_dim
    w, h = img.size
    if max(w, h) > max_dim:
        scale = max_dim / max(w, h)
        img = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=85)
    return base64.b64encode(buf.getvalue()).decode("ascii"), "image/jpeg"


def call_vision(client, paths: list[Path]) -> tuple[list[dict] | None, dict]:
    """Send a batch of images to Sonnet, parse JSON, return per-image results + usage."""
    blocks: list[dict] = []
    for i, p in enumerate(paths, 1):
        bb = downscale_to_b64(p, MAX_DIM)
        if not bb:
            return None, {}
        b64, mt = bb
        blocks.append({
            "type": "text",
            "text": f"Image {i}:",
        })
        blocks.append({
            "type": "image",
            "source": {"type": "base64", "media_type": mt, "data": b64},
        })
    blocks.append({"type": "text", "text": PROMPT.format(n=len(paths))})

    resp = client.messages.create(
        model=MODEL,
        max_tokens=600,
        temperature=0,
        messages=[{"role": "user", "content": blocks}],
    )
    usage = {
        "input": resp.usage.input_tokens,
        "output": resp.usage.output_tokens,
    }
    text = resp.content[0].text.strip()
    # Sonnet sometimes wraps in ```json ... ```; strip
    if text.startswith("```"):
        text = text.split("```", 2)
        if len(text) >= 2:
            text = text[1]
            if text.startswith("json"):
                text = text[4:]
        else:
            text = text[0]
    try:
        data = json.loads(text)
        return data.get("results", []), usage
    except json.JSONDecodeError as e:
        print(f"[!] JSON parse failed: {e}\n{text[:200]}", file=sys.stderr)
        return None, usage


def main():
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        # Pull from project .env
        env = (Path.home() / "gst-cranes/.env").read_text()
        for line in env.splitlines():
            if line.startswith("ANTHROPIC_API_KEY="):
                key = line.split("=", 1)[1].strip().strip("'\"")
                break
    if not key:
        print("[!] ANTHROPIC_API_KEY required", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=key)

    # Load raw labels, filter to needs_vision=True (Photos Library only)
    photos = []
    with RAW_LABELS.open() as f:
        for row in csv.DictReader(f):
            if row["needs_vision"] == "True":
                photos.append(row)
    print(f"[*] {len(photos)} Photos Library rows to verify")

    state = load_state()
    print(f"[*] Already done: {len(state['done'])}. Spent: ${state['spent_usd']:.3f}")

    todo = [p for p in photos if p["image_path"] not in state["done"]]
    print(f"[*] Remaining: {len(todo)}")

    if state["spent_usd"] >= COST_CAP_USD:
        print(f"[!] Already at cost cap ${COST_CAP_USD}. Aborting.")
        sys.exit(2)

    # Batch + run
    batches = [todo[i:i + BATCH] for i in range(0, len(todo), BATCH)]
    print(f"[*] {len(batches)} batches of up to {BATCH}, model={MODEL}, max_dim={MAX_DIM}px")

    start = time.time()
    for bi, batch in enumerate(batches):
        # Pre-check existence
        paths = [Path(p["image_path"]) for p in batch]
        missing = [str(p) for p in paths if not p.exists()]
        if missing:
            # Drop missing, fill state with skip
            for m in missing:
                state["done"][m] = {"skip": True, "reason": "file_missing"}
            paths = [p for p in paths if p.exists()]
            batch = [r for r, p in zip(batch, [Path(r["image_path"]) for r in batch]) if p.exists()]
            if not paths:
                save_state(state)
                continue

        try:
            results, usage = call_vision(client, paths)
        except Exception as e:
            print(f"[!] batch {bi}: {e}", file=sys.stderr)
            time.sleep(2)
            continue

        cost = usage.get("input", 0) * PRICE_IN + usage.get("output", 0) * PRICE_OUT
        state["spent_usd"] += cost

        if not results or len(results) != len(paths):
            print(f"[!] batch {bi}: result count mismatch ({len(results) if results else 'None'} vs {len(paths)})", file=sys.stderr)
            for p in paths:
                state["done"][str(p)] = {"skip": True, "reason": "parse_fail"}
            save_state(state)
            continue

        for p, r in zip(paths, results):
            state["done"][str(p)] = {
                "visible_text": r.get("visible_text", ""),
                "text_confidence": float(r.get("text_confidence", 0.0)),
            }

        # Throttle / progress
        if (bi + 1) % 10 == 0:
            elapsed = time.time() - start
            rate = (bi + 1) / elapsed
            eta = (len(batches) - bi - 1) / rate if rate else 0
            print(f"   [batch {bi+1}/{len(batches)}] spent=${state['spent_usd']:.3f}  rate={rate:.2f}/s  ETA={eta/60:.1f}m")
            save_state(state)

        if state["spent_usd"] >= COST_CAP_USD:
            print(f"[!] HIT COST CAP ${COST_CAP_USD}. Stopping at batch {bi}.")
            save_state(state)
            break

        # 100ms throttle to avoid Anthropic rate-limit spikes
        time.sleep(0.1)

    save_state(state)

    # Apply Vision OCR results to existing labels:
    #   1. If decal text contains a brand keyword → use that (override existing if different)
    #   2. If no brand keyword detected → keep existing label (Vision couldn't see decal,
    #      doesn't mean the existing label is wrong)
    #   3. Also extract model from decal text when possible (overrides existing model)
    clean_rows = []
    review_rows = []
    overrides = 0
    kept_existing = 0
    for row in photos:
        r = state["done"].get(row["image_path"])
        if not r or r.get("skip"):
            kept_existing += 1
            clean_rows.append({
                "image_path": row["image_path"],
                "brand": row["brand"],
                "model": row["model"] or None,
                "confidence": 0.5,  # Vision didn't see this one, low-medium confidence
                "source": "photos_existing",
            })
            continue
        visible_text = r.get("visible_text", "")
        text_conf = r.get("text_confidence", 0.0)

        detected_brand = detect_brand_from_text(visible_text)

        if detected_brand:
            detected_model = detect_model_from_text(visible_text, detected_brand)
            # Decal-verified label
            if detected_brand != row["brand"]:
                overrides += 1
            clean_rows.append({
                "image_path": row["image_path"],
                "brand": detected_brand,
                "model": detected_model,  # may be None
                "confidence": min(0.95, 0.7 + text_conf * 0.25),  # 0.7-0.95 range
                "source": "photos_vision_verified",
            })
        else:
            # No brand keyword in decal → can't verify, but don't downgrade existing label.
            # Keep existing label at reduced confidence (Vision couldn't corroborate).
            kept_existing += 1
            clean_rows.append({
                "image_path": row["image_path"],
                "brand": row["brand"],
                "model": row["model"] or None,
                "confidence": 0.4,
                "source": "photos_existing_unverified",
            })
            # Flag for review if text_conf was high but no brand match (suspicious)
            if text_conf > 0.6 and visible_text:
                review_rows.append({
                    "image_path": row["image_path"],
                    "old_brand": row["brand"],
                    "old_model": row["model"],
                    "vision_brand": None,
                    "vision_model": None,
                    "confidence": text_conf,
                    "decal_text": visible_text,
                })

    print(f"\n[*] Vision-verified overrides: {overrides}")
    print(f"[*] Kept existing (no decal evidence): {kept_existing}")

    # Also pass through manifest rows (no Vision needed)
    with RAW_LABELS.open() as f:
        for row in csv.DictReader(f):
            if row["source"] == "manifest":
                clean_rows.append({
                    "image_path": row["image_path"],
                    "brand": row["brand"],
                    "model": row["model"],
                    "confidence": 1.0,
                    "source": "manifest",
                })

    with CLEAN_OUT.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["image_path", "brand", "model", "confidence", "source"])
        w.writeheader()
        w.writerows(clean_rows)
    with REVIEW_OUT.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["image_path", "old_brand", "old_model", "vision_brand", "vision_model", "confidence", "decal_text"])
        w.writeheader()
        w.writerows(review_rows)

    print(f"\n[*] Final spent: ${state['spent_usd']:.3f}")
    print(f"[*] Wrote {len(clean_rows)} clean rows → {CLEAN_OUT}")
    print(f"[*] Wrote {len(review_rows)} review rows → {REVIEW_OUT}")


if __name__ == "__main__":
    main()
